---
# hosts.yml - Example inventory for installing vantage agents

utility:
  hosts:
    utility-host-1:
      ansible_host: 192.168.1.100
      ansible_user: ubuntu
      # Add any host-specific variables here
